### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by ignacio-dev** [WebLogin/laravel-lookup#1]
I get the following message after calling the `collection()` method

`PHP Deprecated:  Return type of WebLogin\LaravelLookup\Lookup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/weblogin/laravel-lookup/src/Lookup.php on line 89`

**Comment by Mushr0000m** [comment]
Hi ! Can you give more informations please like the Laravel version you use, PHP version and also the line of code where you use Lookup and have this error. Thanks

**Comment by ignacio-dev** [comment]
Yes, of course!

**Laravel v9.19**

I copy your code for the class, but place it in a directory called StaticModels

```
<?php

namespace App\StaticModels;

use WebLogin\LaravelLookup\Lookup;

class CarEngineLookup extends Lookup
{
    public $key;
    public $name;


    protected static function getItems()
    {
        return [
            ['key' => 'gas',    'name' => "Gasoline"],
            ['key' => 'elec',   'name' => "Electric"],
            ['key' => 'hyb',    'name' => "Hybrid"],
        ];
    }
}
```

Then on Tinker:

```
use App\StaticModels\CarEngineLookup;
CarEngineLookup::collection();
```

It returns:

```
PHP Deprecated:  Return type of WebLogin\LaravelLookup\Lookup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/weblogin/laravel-lookup/src/Lookup.php on line 89
=> WebLogin\LaravelLookup\LookupCollection {#3713
     all: [
       App\StaticModels\CarEngineLookup {#3710
         +key: "gas",
         +name: "Gasoline",
       },
       App\StaticModels\CarEngineLookup {#3717
         +key: "elec",
         +name: "Electric",
       },
       App\StaticModels\CarEngineLookup {#3719
         +key: "hyb",
         +name: "Hybrid",
       },
     ],
   }
```

**Comment by ignacio-dev** [comment]
I updated the comment to add the PHP version, as I had forgotten

**Comment by Mushr0000m** [comment]
Ok so from what I see it's an issue with Laravel Collection and PHP 8.1, I only had PHP 8.0 installed. I tried it and have the same warning. Other projects had the same error like https://github.com/tighten/collect/issues/261. I will fix this quickly ;-)

**Comment by Mushr0000m** [comment]
My bad it was a missing return signature. Update to latest version it should be good.

**Comment by ignacio-dev** [comment]
Works like a charm now, thank you much!!!
