### ISSUE TITLE
LookupCollectionCast returns object instead of array when converted to JSON

### ISSUE THREAD

**Issue by ignacio-dev** [WebLogin/laravel-lookup#4]
Hello,

I have a ```Product``` model that has a ```materials``` attribute that casts to a ```ProductMaterialLookup``` collection like this:

```
protected $casts = [
    'materials' => LookupCollectionCast::class.':'. ProductMaterialLookup::class,
];
```

This works great, but when returning JSON by calling ```return $product``` on my Controller, the ```ProductMaterialLookup``` is returning an object with an index as an attribute:

```
"materials": {
    "2": {
        "key": "cotton",
        "text": "Cotton"
    },
    "7": {
        "key": "polyester",
        "text": "Polyester"
    }
}
```

Instead of (what I expected) :
```
"materials": [
    {
        "key": "cotton",
        "text": "Cotton"
    },
    {
        "key": "polyester",
        "text": "Polyester"
    }
]
```

**Comment by Mushr0000m** [comment]
Sorry for that, I'll push a fix quickly.

**Comment by Mushr0000m** [comment]
Please update, it's fixed ;-)

**Comment by ignacio-dev** [comment]
You are amazing, thank you so much!!

**Comment by ignacio-dev** [comment]
Hello, I'm having this issue again, when I use ```CountryLookup::where('canSellOnPlatorm', TRUE)```, or when I use ```CountryLookup::all()```. Works fine when I do ```CountryLookup::collection()``` though.

**Comment by Mushr0000m** [comment]
Hi, sorry for the long delay I was quite overbooked. I'm not sure to understand the issue, when you give the example `CountryLookup::where('canSellOnPlatorm', TRUE)` it's normal behavior of Laravel collection, you have to call `values()` to reset the keys https://laravel.com/docs/10.x/collections#method-values . Or maybe I didn't well understood your issue ?
